<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ListadoPacientes.aspx.cs" Inherits="Vistas.ListadoPacientes" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Listado de Pacientes</title>
<style type="text/css">
 body {
    min-height: 100vh;
    background-image: url(./img_vistas/fachadaClinica.jpg);
    background-repeat: no-repeat;
    margin: 0;
    background-size: cover;
    display: flex;
    justify-content: center;
    align-items: center;
 }

 .navbar {
     background-color: #333;
     overflow: hidden;
     position: fixed; 
     top: 0;
     left: 0;
     width: 100%;
     z-index: 1000;
 }

 .navbar a {
     float: left;
     color: white;
     text-align: center;
     padding: 14px 20px;
     text-decoration: none;
 }

 .navbar a:hover {
     background-color: #ddd;
     color: black;
 }

 .contenido {
      margin-top: 90px; 
      background-color: rgba(0,0,0,0.55);
      padding: 30px;
      border-radius: 12px;
      max-width: 90%;
      text-align: left;
      margin-left: auto;
      margin-right: auto;
      box-shadow: 0 4px 12px rgba(0,0,0,0.4);
 }

 .usuario {
     text-align: right;
     margin-bottom: 10px;
     color: #f1f1f1;
     font-weight: bold;
 }
    
 h1 {
      margin: 10px 0 8px 0;
      color: #fff;
 }
 .listado_Pacientes {
    background-color: white;
    padding: 20px;
    border-radius: 10px;
    overflow-x: auto;
}

#gvListaPacientes {
    width: 100%;
    min-width: 1500px;
}

#gvListaPacientes a {
    color: blue !important;
    font-weight: bold;
}




</style>
</head>
<body>
    <form id="form1" runat="server">
        <!-- Navbar -->
        <div class="navbar">
            <a href="Home.aspx">Inicio</a>
            <a href="HomeMedicos.aspx">Médicos</a>
            <a href="HomeTurnos.aspx">Turnos</a>
            <a href="HomePacientes.aspx">Pacientes</a>
            <a href="HomeUsuarios.aspx">Usuarios</a>
            <a href="Informes.aspx">Informes</a>
            <a href="InterfazLoguin.aspx">Login</a>
        </div>

        <div class="contenido">            
            <div class="usuario">
                <asp:Label ID="lblUsuario" runat="server"></asp:Label>
                <asp:Label ID="lblFecha" runat="server"></asp:Label>
            </div>
            
            <h1>Listado de Pacientes&nbsp;&nbsp;&nbsp;
                <asp:Label ID="Label1" runat="server" Font-Size="Smaller" Text="buscar por DNI:"></asp:Label>
                <asp:TextBox ID="txtBuscarPorDNI" runat="server" Height="26px" Width="291px"></asp:TextBox>
&nbsp;&nbsp;
                <asp:Button ID="btnBuscar" runat="server" OnClick="btnBuscar_Click" Text="Buscar" />
            &nbsp;&nbsp;
                <asp:Button ID="btnMostrarTodos" runat="server" OnClick="btnMostrarTodos_Click" Text="MostrarTodos" />
            </h1>

            <div class="listado_Pacientes">
                <asp:GridView ID="gvListaPacientes" 
                    runat="server" 
                    AutoGenerateColumns="False"
                    AutoGenerateDeleteButton="True"
                    AutoGenerateEditButton="True"
                    AllowPaging="True"
                    PageSize="10"
                    OnPageIndexChanging="gvListaPacientes_PageIndexChanging"
                    DataKeyNames="IdPaciente"
                    BackColor="White" 
                    BorderColor="#336666" 
                    BorderStyle="Double" 
                    BorderWidth="3px" 
                    CellPadding="4" 
                    GridLines="Horizontal" 
                    OnRowDeleting="gvListaPacientes_RowDeleting"
                    OnRowEditing="gvListaPacientes_RowEditing"    
                    OnRowCancelingEdit="gvListaPacientes_RowCancelingEdit"
                    OnRowUpdating="gvListaPacientes_RowUpdating"
                    OnRowDataBound="gvListaPacientes_RowDataBound"
                    OnSelectedIndexChanged="gvListaPacientes_SelectedIndexChanged1">

    <Columns>

        
        <asp:BoundField DataField="IdPaciente" HeaderText="ID" ReadOnly="true" />

       
        <asp:TemplateField HeaderText="Nombre">
            <ItemTemplate>
                <%# Eval("Nombre") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtNombre" runat="server" Text='<%# Bind("Nombre") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

       
        <asp:TemplateField HeaderText="Apellido">
            <ItemTemplate>
                <%# Eval("Apellido") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtApellido" runat="server" Text='<%# Bind("Apellido") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

      
        <asp:TemplateField HeaderText="DNI">
            <ItemTemplate>
                <%# Eval("Dni") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtDni" runat="server" Text='<%# Bind("Dni") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

       
        <asp:TemplateField HeaderText="Sexo">
            <ItemTemplate>
                <%# Eval("sexo") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:DropDownList ID="ddlSexo" runat="server" />
            </EditItemTemplate>
        </asp:TemplateField>

        
        <asp:TemplateField HeaderText="Nacionalidad">
            <ItemTemplate>
                <%# Eval("Nacionalidad") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtNacionalidad" runat="server" Text='<%# Bind("Nacionalidad") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

       
        <asp:TemplateField HeaderText="Nacimiento">
            <ItemTemplate>
                <%# Eval("FechaNacimiento", "{0:yyyy-MM-dd}") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox
                    ID="txtFechaNacimiento"
                    runat="server"
                    TextMode="Date"
                    Text='<%# Bind("fechaNacimiento", "{0:yyyy-MM-dd}") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

        
        <asp:TemplateField HeaderText="Dirección">
            <ItemTemplate>
                <%# Eval("Direccion") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtDireccion" runat="server" Text='<%# Bind("Direccion") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

       <asp:TemplateField HeaderText="Provincia">
            <ItemTemplate>
                <%# Eval("provincia") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:DropDownList
                    ID="ddlProvincias"
                    OnSelectedIndexChanged="ddlProvincias_SelectedIndexChanged"
                    AutoPostBack="true"
                    runat="server" />
            </EditItemTemplate>
        </asp:TemplateField>

        <asp:TemplateField HeaderText="Localidad">
            <ItemTemplate>
                <%# Eval("localidad") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:DropDownList ID="ddlLocalidades" runat="server" />
            </EditItemTemplate>
        </asp:TemplateField>
        
        <asp:TemplateField HeaderText="Correo">
            <ItemTemplate>
                <%# Eval("CorreoElectronico") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtCorreo" runat="server" Text='<%# Bind("CorreoElectronico") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

        
        <asp:TemplateField HeaderText="Teléfono">
            <ItemTemplate>
                <%# Eval("Telefono") %>
            </ItemTemplate>
            <EditItemTemplate>
                <asp:TextBox ID="txtTelefono" runat="server" Text='<%# Bind("Telefono") %>' />
            </EditItemTemplate>
        </asp:TemplateField>

    </Columns>

    <FooterStyle BackColor="White" ForeColor="#333333" />
    <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
    <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
    <RowStyle ForeColor="#333333" BackColor="White" />
    <SortedAscendingCellStyle BackColor="#F7F7F7" />
    <SortedAscendingHeaderStyle BackColor="#487575" />
    <SortedDescendingCellStyle BackColor="#E5E5E5" />
    <SortedDescendingHeaderStyle BackColor="#275353" />

</asp:GridView>

                <asp:Label ID="lblMensaje" runat="server" ForeColor="Red"></asp:Label>
            </div>
        </div>
    </form>
</body>
</html>
