<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ListadoMedicos.aspx.cs" Inherits="Vistas.WebForm1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
<style type="text/css">

 body{
    height: 100vh;
    background-image:url(./img_vistas/fachadaClinica.jpg);
    background-repeat:no-repeat;
    margin:0;
    background-size: cover;
    display: flex;
    justify-content: center;
    align-items: center;
  }

 .navbar {
     background-color: #333;
     overflow: hidden;
     position: fixed; 
     top: 0;
     left: 0;
     width: 100%;
     z-index: 1000;
 }

 .navbar a {
     float: left;
     color: white;
     text-align: center;
     padding: 14px 20px;
     text-decoration: none;
 }

 .navbar a:hover {
     background-color: #ddd;
     color: black;
 }

 .usuario {
   text-align: right;
   margin-bottom: 10px;
   color: #f1f1f1;
   font-weight: bold;
 }

 .contenido {
      margin-top: 90px;
      background-color: rgba(0,0,0,0.55);
      padding: 30px;
      border-radius: 12px;
      max-width: 90%;
      width: 100%;
      text-align: left;
      margin-left: auto;
      margin-right: auto;
      box-shadow: 0 4px 12px rgba(0,0,0,0.4);
      overflow-x: scroll;
 }


    
 h1{
      margin: 10px 0 8px 0;
      color: #fff;
 }

 #form1 {
     max-width: 90%;
 }

 .boton {
    background-color: #5a9;
    color: #fff;
    padding: 10px 16px;
    border-radius: 6px;
    text-decoration: none;
    display:inline-block;
}

.boton:hover {
    opacity: 0.9;
}

</style>
</head>
<body>
    <form id="form1" runat="server">
             <!-- navbar-->
      <div class="navbar">
          <a href="Home.aspx">Inicio</a>
          <a href="HomeMedicos.aspx">Médico</a>
          <a href="HomeTurnos.aspx">Turnos</a>
          <a href="HomePacientes.aspx">Pacientes</a>
          <a href="HomeUsuarios.aspx">Usuarios</a>
          <a href="Informes.aspx">Informes</a>
          <a href="InterfazLoguin.aspx">Login</a>
      </div>

      <div class="contenido">
          <div class="usuario">
              <asp:Label ID="lblUsuario" runat="server"></asp:Label>
              <asp:Label ID="lblFecha" runat="server"></asp:Label>
          </div>
          <a class="boton" href="HomeMedicos.aspx">Volver al menú Médicos</a>
          <h1>Listado de médicos&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <asp:Label ID="lblMedicos" runat="server" Font-Size="Smaller" Text="Buscar medicos por DNI:"></asp:Label>
&nbsp;<asp:TextBox ID="txtDNI" runat="server" Height="24px" TextMode="Number"></asp:TextBox>
&nbsp;
              <asp:Button ID="btnBuscarMedico" runat="server" Height="39px" OnClick="btnBuscarMedico_Click" style="margin-top: 0px" Text="Buscar" Width="137px" />
              <asp:Button ID="btnMostrarTodos" runat="server" Height="39px" OnClick="btnMostrarTodos_Click" style="margin-top: 0px" Text="Mostrar todos" Width="137px" />
          
          </h1>
           <div class="listado_Medicos">
               <asp:GridView
                   ID="gvListaMedicos"
                   runat="server"
                   AutoGenerateColumns="False"
                   AutoGenerateDeleteButton="True"
                   AutoGenerateEditButton="True"
                   AllowPaging="True"
                   PageSize="10"
                   OnPageIndexChanging="gvListaMedicos_PageIndexChanging"
                   OnRowEditing="gvListaMedicos_RowEditing"
                   OnRowUpdating="gvListaMedicos_RowUpdating"
                   OnRowCancelingEdit="gvListaMedicos_RowCancelingEdit"
                   OnRowDataBound="gvListaMedicos_RowDataBound"
                   OnRowDeleting ="gvListaMedicos_RowDeleting"
                   DataKeyNames="idMedico, idUsuario"
                   BackColor="White"
                   BorderColor="#336666"
                   BorderStyle="Double"
                   BorderWidth="3px"
                   CellPadding="4"
                   GridLines="Horizontal"
               >
                   <Columns>
                        <asp:BoundField DataField="idMedico" HeaderText="ID"  ReadOnly="True" />

                        <asp:TemplateField HeaderText="Legajo">
                            <ItemTemplate>
                                <%# Eval("legajo") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtLegajo" runat="server" Text='<%# Bind("legajo") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="DNI">
                            <ItemTemplate>
                                <%# Eval("dni") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtDni" runat="server" Text='<%# Bind("dni") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Nombre">
                            <ItemTemplate>
                                <%# Eval("nombre") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtNombre" runat="server" Text='<%# Bind("nombre") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Apellido">
                            <ItemTemplate>
                                <%# Eval("apellido") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtApellido" runat="server" Text='<%# Bind("apellido") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Sexo">
                            <ItemTemplate>
                                <%# Eval("sexo") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="ddlSexo" runat="server" />
                            </EditItemTemplate>
                        </asp:TemplateField>


                        <asp:TemplateField HeaderText="Nacionalidad">
                            <ItemTemplate>
                                <%# Eval("nacionalidad") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtNacionalidad" runat="server" Text='<%# Bind("nacionalidad") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Fecha de nacimiento">
                            <ItemTemplate>
                                <%# Eval("fechaNacimiento", "{0:dd/MM/yyyy}") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox
                                    ID="txtFechaNacimiento"
                                    runat="server"
                                    TextMode="Date"
                                    Text='<%# Bind("fechaNacimiento", "{0:yyyy-MM-dd}") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Provincia">
                            <ItemTemplate>
                                <%# Eval("provincia") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList
                                    ID="ddlProvincias"
                                    OnSelectedIndexChanged="ddlProvincias_SelectedIndexChanged"
                                    AutoPostBack="true"
                                    runat="server" />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Localidad">
                            <ItemTemplate>
                                <%# Eval("localidad") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="ddlLocalidades" runat="server" />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Dirección">
                            <ItemTemplate>
                                <%# Eval("direccion") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtDireccion" runat="server" Text='<%# Bind("direccion") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Correo electrónico">
                            <ItemTemplate>
                                <%# Eval("correoElectronico") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtCorreoElectronico" runat="server" Text='<%# Bind("correoElectronico") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Teléfono">
                            <ItemTemplate>
                                <%# Eval("telefono") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:TextBox ID="txtTelefono" runat="server" Text='<%# Bind("telefono") %>' />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:TemplateField HeaderText="Especialidad">
                            <ItemTemplate>
                                <%# Eval("especialidad") %>
                            </ItemTemplate>
                            <EditItemTemplate>
                                <asp:DropDownList ID="ddlEspecialidades" runat="server" />
                            </EditItemTemplate>
                        </asp:TemplateField>

                        <asp:BoundField DataField="Usuario" HeaderText="Usuario"  ReadOnly="True" />

                   </Columns>

                   <FooterStyle BackColor="White" ForeColor="#333333" />
                   <HeaderStyle BackColor="#336666" Font-Bold="True" ForeColor="White" />
                   <PagerStyle BackColor="#336666" ForeColor="White" HorizontalAlign="Center" />
                   <RowStyle ForeColor="#333333" BackColor="White" />
                   <SortedAscendingCellStyle BackColor="#F7F7F7" />
                   <SortedAscendingHeaderStyle BackColor="#487575" />
                   <SortedDescendingCellStyle BackColor="#E5E5E5" />
                   <SortedDescendingHeaderStyle BackColor="#275353" />
               </asp:GridView>
           </div>
      </div>
        <div>
            <asp:Label ID="lblMensaje" runat="server"></asp:Label>
        </div>
    </form>
</body>
</html>

